easy_admin:
    design:
        menu:
            - { route: 'dashboard_index', label: 'Dashboard', icon: 'tachometer' }
            - label: 'Administrator'
              role: '%env(string:SEMART_SECURITY_USER_MENU)%'
              icon: 'shield'
              children:
                  - { entity: 'User', label: 'User', icon: 'hand-o-right', params: { sortField: 'createdAt', sortDirection: 'DESC' } }
                  - { entity: 'Setting', label: 'Konfigurasi', icon: 'hand-o-right' }
            - label: 'Master'
              role: '%env(string:SEMART_SECURITY_MASTER_MENU)%'
              icon: 'database'
              children:
                  - { entity: 'EducationalInstitute', label: 'Lembaga Pendidikan', icon: 'hand-o-right', params: { sortField: 'createdAt', sortDirection: 'DESC' } }
                  - { entity: 'EducationTitle', label: 'Gelar Pendidikan', icon: 'hand-o-right', params: { sortField: 'createdAt', sortDirection: 'DESC' } }
                  - { entity: 'SkillGroup', label: 'Grup Keahlian', icon: 'hand-o-right', params: { sortField: 'createdAt', sortDirection: 'DESC' } }
                  - { entity: 'Skill', label: 'Keahlian', icon: 'hand-o-right', params: { sortField: 'createdAt', sortDirection: 'DESC' } }
                  - { entity: 'Region', label: 'Propinsi', icon: 'hand-o-right', params: { sortField: 'createdAt', sortDirection: 'DESC' } }
                  - { entity: 'City', label: 'Kota', icon: 'hand-o-right', params: { sortField: 'createdAt', sortDirection: 'DESC' } }
                  - { entity: 'Contract', label: 'Kontrak/Surat Keputusan', icon: 'hand-o-right', params: { sortField: 'createdAt', sortDirection: 'DESC' } }
                  - { entity: 'Holiday', label: 'Hari Libur', icon: 'hand-o-right', params: { sortField: 'createdAt', sortDirection: 'DESC' } }
            - label: 'Perusahaan'
              role: '%env(string:SEMART_SECURITY_COMPANY_MENU)%'
              icon: 'building'
              children:
                  - { entity: 'Company', label: 'Perusahaan', icon: 'hand-o-right', params: { sortField: 'createdAt', sortDirection: 'DESC' }, default: true }
                  - { entity: 'Department', label: 'Departemen', icon: 'hand-o-right', params: { sortField: 'createdAt', sortDirection: 'DESC' } }
                  - { entity: 'JobLevel', label: 'Level Jabatan', icon: 'hand-o-right', params: { sortField: 'createdAt', sortDirection: 'DESC' } }
                  - { entity: 'JobTitle', label: 'Jabatan', icon: 'hand-o-right', params: { sortField: 'createdAt', sortDirection: 'DESC' } }
                  - { entity: 'CompanyCost', label: 'Beban Gaji Perusahaan', icon: 'hand-o-right', params: { sortField: 'createdAt', sortDirection: 'DESC' } }
            - label: 'Karyawan'
              role: '%env(string:SEMART_SECURITY_EMPLOYEE_MENU)%'
              icon: 'user-md'
              children:
                  - { entity: 'Employee', label: 'Profil Karyawan', icon: 'hand-o-right', params: { sortField: 'createdAt', sortDirection: 'DESC' } }
                  - { entity: 'Placement', label: 'Penempatan Karyawan', icon: 'hand-o-right', params: { sortField: 'createdAt', sortDirection: 'DESC' } }
                  - { entity: 'Mutation', label: 'Mutasi Karyawan', icon: 'hand-o-right', params: { sortField: 'createdAt', sortDirection: 'DESC' } }
                  - { entity: 'CareerHistory', label: 'Riwayat Karir', icon: 'hand-o-right', params: { sortField: 'createdAt', sortDirection: 'DESC' } }
                  - { entity: 'TaxGroup', label: 'Perubahan Pajak', icon: 'hand-o-right', params: { sortField: 'createdAt', sortDirection: 'DESC' } }
            - label: 'Absensi'
              role: '%env(string:SEMART_SECURITY_ATTENDANCE_MENU)%'
              icon: 'clock-o'
              children:
                  - { entity: 'AbsentReason', label: 'Alasan Ketidakhadiran', icon: 'hand-o-right', params: { sortField: 'createdAt', sortDirection: 'DESC' } }
                  - { entity: 'Shiftment', label: 'Shift Kerja', icon: 'hand-o-right', params: { sortField: 'createdAt', sortDirection: 'DESC' } }
                  - { entity: 'Workshift', label: 'Jadwal Kerja', icon: 'hand-o-right', params: { sortField: 'startDate', sortDirection: 'DESC' } }
                  - { entity: 'Attendance', label: 'Absensi', icon: 'hand-o-right', params: { sortField: 'attendanceDate', sortDirection: 'DESC' } }
                  - { entity: 'AttendanceSummary', label: 'Riwayat Absensi', icon: 'hand-o-right', params: { sortField: 'createdAt', sortDirection: 'DESC' } }
            - label: 'Lembur'
              role: '%env(string:SEMART_SECURITY_OVERTIME_MENU)%'
              icon: 'list-alt'
              children:
                  - { entity: 'Overtime', label: 'Lembur', icon: 'hand-o-right', params: { sortField: 'overtimeDate', sortDirection: 'DESC' } }
            - label: 'Cuti'
              role: '%env(string:SEMART_SECURITY_LEAVE_MENU)%'
              icon: 'envelope-o'
              children:
                  - { entity: 'LeaveReason', label: 'Alasan Cuti', icon: 'hand-o-right', params: { sortField: 'createdAt', sortDirection: 'DESC' } }
                  - { entity: 'Leave', label: 'Cuti', icon: 'hand-o-right', params: { sortField: 'createdAt', sortDirection: 'DESC' } }
            - label: 'Penggajian'
              role: '%env(string:SEMART_SECURITY_PAYROLL_MENU)%'
              icon: 'money'
              children:
                  - { entity: 'SalaryComponent', label: 'Komponen Gaji', icon: 'hand-o-right', params: { sortField: 'createdAt', sortDirection: 'DESC' } }
                  - { entity: 'SalaryBenefit', label: 'Setting Gaji', icon: 'hand-o-right', params: { sortField: 'createdAt', sortDirection: 'DESC' } }
                  - { entity: 'SalaryBenefitHistory', label: 'Perubahan Gaji', icon: 'hand-o-right', params: { sortField: 'createdAt', sortDirection: 'DESC' } }
                  - { entity: 'SalaryAllowancePlus', label: 'Tunjangan', icon: 'hand-o-right', params: { sortField: 'year', sortDirection: 'DESC', state: 'p' } }
                  - { entity: 'SalaryAllowanceMinus', label: 'Potongan', icon: 'hand-o-right', params: { sortField: 'year', sortDirection: 'DESC', state: 'm' } }
                  - { entity: 'PayrollPeriod', label: 'Penggajian', icon: 'hand-o-right', params: { sortField: 'year', sortDirection: 'DESC' } }
                  - { entity: 'Payroll', label: 'Riwayat Penggajian', icon: 'hand-o-right', params: { sortField: 'createdAt', sortDirection: 'DESC' } }
                  - { entity: 'Tax', label: 'Pajak PPH21', icon: 'hand-o-right', params: { sortField: 'createdAt', sortDirection: 'DESC' } }
            - label: 'Alamat'
              role: '%env(string:SEMART_SECURITY_ADDRESS_MENU)%'
              icon: 'id-card-o'
              children:
                  - { entity: 'CompanyAddress', label: 'Alamat Perusahaan', icon: 'hand-o-right', params: { sortField: 'createdAt', sortDirection: 'DESC' } }
                  - { entity: 'EmployeeAddress', label: 'Alamat Karyawan', icon: 'hand-o-right', params: { sortField: 'createdAt', sortDirection: 'DESC' } }
