easy_admin:
    entities:
        Overtime:
            role: '%env(string:SEMART_SECURITY_OVERTIME_MENU)%'
            class: 'KejawenLab\Application\SemartHris\Entity\Overtime'
            controller: 'KejawenLab\Application\SemartHris\Controller\Admin\OvertimeController'
            disabled_actions: ['search']
            templates:
                new: 'app/attendance/new.html.twig'
                list: 'app/overtime/list.html.twig'
                edit: 'app/attendance/edit.html.twig'
            new:
                title: 'Tambah Lembur'
            edit:
                title: 'Edit Lembur'
            form:
                fields:
                    - { type: 'group', css_class: 'col-sm-6' }
                    - { property: 'employee', label: 'Karyawan', type: 'easyadmin_autocomplete' }
                    - { property: 'overtimeDate', label: 'Tanggal', help: 'Ganti tanggal otomatis dihitung jika jam masuk lebih besar dari jam keluar', type_options:{ format: '%env(string:SEMART_DATE_FORMAT_INTL)%', attr: { class: 'date-picker' }, widget: 'single_text' } }
                    - { type: 'group', css_class: 'col-sm-6' }
                    - { property: 'startHour', label: 'Jam Masuk', type_options:{ attr: { class: 'time-picker' }, widget: 'single_text' } }
                    - { property: 'endHour', label: 'Jam Keluar', help: 'Hari libur dicentang jika lembur dihari libur/off', type_options:{ attr: { class: 'time-picker' }, widget: 'single_text' } }
                    - { property: 'holiday', label: 'Hari Libur?' }
                    - { type: 'group', css_class: 'col-sm-12 new-row' }
                    - { property: 'description', label: 'Keterangan' }
            show:
                title: 'Detil Lembur'
                fields:
                    - { property: 'overtimeDate', label: 'Tanggal' }
                    - { property: 'employee', label: 'Karyawan' }
                    - { property: 'shiftment', label: 'Shift' }
                    - { property: 'startHour', label: 'Jam Masuk' }
                    - { property: 'endHour', label: 'Jam Keluar' }
                    - { property: 'overday', label: 'Ganti Tanggal?' }
                    - { property: 'rawValue', label: 'Jam' }
                    - { property: 'calculatedValue', label: 'Jumlah' }
                    - { property: 'holiday', label: 'Hari Libur?' }
                    - { property: 'approved', label: 'Disetujui?', type: 'boolean' }
                    - { property: 'approvedBy', label: 'Disetujui oleh' }
                    - { property: 'description', label: 'Keterangan' }
            list:
                role: '%env(string:SEMART_SECURITY_OVERTIME_MENU)%'
                title: 'Lembur'
                fields:
                    - { property: 'overtimeDate', label: 'Tanggal' }
                    - { property: 'employee', label: 'Karyawan' }
                    - { property: 'shiftment', label: 'Shift' }
                    - { property: 'startHour', label: 'Jam Masuk' }
                    - { property: 'endHour', label: 'Jam Keluar' }
                    - { property: 'overday', label: 'Ganti Tanggal?', type: 'boolean' }
                    - { property: 'holiday', label: 'Libur?', type: 'boolean' }
                    - { property: 'approved', label: 'Disetujui?', type: 'boolean' }
                    - { property: 'description', label: 'Keterangan', type: 'raw' }
