easy_admin:
    entities:
        PayrollPeriod:
            role: '%env(string:SEMART_SECURITY_PAYROLL_MENU)%'
            class: 'KejawenLab\Application\SemartHris\Entity\PayrollPeriod'
            controller: 'KejawenLab\Application\SemartHris\Controller\Admin\AdminController'
            disabled_actions: ['show', 'search', 'edit', 'delete']
            templates:
                list: 'app/payroll/list.html.twig'
            search:
                title: 'Penggajian'
            list:
                role: '%env(string:SEMART_SECURITY_PAYROLL_MENU)%'
                title: 'Penggajian'
                fields:
                    - { property: 'company', label: 'Perusahaan' }
                    - { property: 'year', label: 'Tahun', type: 'text' }
                    - { property: 'month', label: 'Bulan', type: 'text', template: 'app/default/field_month.html.twig' }
                    - { property: 'closed', label: 'Aktif?', template: 'app/default/field_boolean_negation.html.twig' }

        SalaryBenefit:
            role: '%env(string:SEMART_SECURITY_PAYROLL_MENU)%'
            class: 'KejawenLab\Application\SemartHris\Entity\SalaryBenefit'
            controller: 'KejawenLab\Application\SemartHris\Controller\Admin\SalaryBenefitController'
            disabled_actions: ['show', 'edit', 'delete', 'search']
            templates:
                new: 'app/payroll/new.html.twig'
                list: 'app/salary/list.html.twig'
            new:
                title: 'Setting Gaji'
            edit:
                title: 'Setting Gaji'
            search:
                title: 'Setting Gaji'
                fields: ['employee']
            form:
                fields:
                    - { type: 'group', css_class: 'col-sm-6' }
                    - { property: 'employee', label: 'Karyawan', type: 'easyadmin_autocomplete' }
                    - { type: 'group', css_class: 'col-sm-6' }
                    - { property: 'component', type: 'hidden', type_options: { attr: { class: 'component-id' } } }
                    - { property: 'component_text', label: 'Komponen Gaji', type: 'choice', type_options: { required: true, attr: { class: 'component-select' }, mapped: false, choices: { 'label.form.empty_value': '' } } }
                    - { type: 'group', css_class: 'col-sm-12 new-row' }
                    - { property: 'benefitValue', label: 'Nilai', type: 'text', type_options: { attr: { class: 'positive' } } }
            list:
                role: '%env(string:SEMART_SECURITY_PAYROLL_MENU)%'
                title: 'Setting Gaji'
                fields:
                    - { property: 'employee', label: 'Karyawan' }
                    - { property: 'component', label: 'Komponen Gaji' }
                    - { property: 'component.fixed', label: 'Tetap?', type: 'boolean' }
                    - { property: 'benefitValue', label: 'Nilai', type: 'float', template: 'app/default/field_currency.html.twig' }

        SalaryBenefitHistory:
            role: '%env(string:SEMART_SECURITY_PAYROLL_MENU)%'
            class: 'KejawenLab\Application\SemartHris\Entity\SalaryBenefitHistory'
            controller: 'KejawenLab\Application\SemartHris\Controller\Admin\SalaryBenefitHistoryController'
            disabled_actions: ['show', 'edit', 'delete', 'search']
            templates:
                new: 'app/salary/change_benefit.html.twig'
                list: 'app/salary/list.html.twig'
            new:
                title: 'Perubahan Gaji'
            edit:
                title: 'Perubahan Gaji'
            search:
                title: 'Perubahan Gaji'
                fields: ['employee']
            form:
                fields:
                    - { type: 'group', css_class: 'col-sm-6' }
                    - { property: 'employee', label: 'Karyawan' }
                    - { type: 'group', css_class: 'col-sm-6' }
                    - { property: 'contract', type: 'hidden', type_options: { attr: { class: 'contract-id' } } }
                    - { property: 'contract_text', label: 'Surat Keputusan', type: 'choice', type_options: { required: true, attr: { class: 'contract-select' }, mapped: false, choices: { 'label.form.empty_value': '' } } }
                    - { type: 'group', css_class: 'col-sm-6 new-row' }
                    - { property: 'component', type: 'hidden', type_options: { attr: { class: 'component-id' } } }
                    - { property: 'component_text', label: 'Komponen Gaji', type: 'choice', type_options: { required: true, attr: { class: 'component-select' }, mapped: false, choices: { 'label.form.empty_value': '' } } }
                    - { type: 'group', css_class: 'col-sm-6' }
                    - { property: 'newBenefitValue', label: 'Nilai', type: 'text', type_options: { attr: { class: 'positive' } } }
            list:
                role: '%env(string:SEMART_SECURITY_PAYROLL_MENU)%'
                title: 'Perubahan Gaji'
                fields:
                    - { property: 'employee', label: 'Karyawan' }
                    - { property: 'component', label: 'Komponen Gaji' }
                    - { property: 'component.fixed', label: 'Tetap?', type: 'boolean' }
                    - { property: 'newbenefitValue', label: 'Nilai Baru', type: 'float', template: 'app/default/field_currency.html.twig' }
                    - { property: 'oldbenefitValue', label: 'Nilai Lama', type: 'float', template: 'app/default/field_currency.html.twig' }

        Payroll:
            role: '%env(string:SEMART_SECURITY_PAYROLL_MENU)%'
            class: 'KejawenLab\Application\SemartHris\Entity\Payroll'
            controller: 'KejawenLab\Application\SemartHris\Controller\Admin\PayrollController'
            disabled_actions: ['show', 'search', 'new', 'edit', 'delete']
            templates:
                list: 'app/payroll/history.html.twig'
            search:
                title: 'Riwayat Penggajian'
            list:
                role: '%env(string:SEMART_SECURITY_PAYROLL_MENU)%'
                title: 'Riwayat Penggajian'
                actions:
                    - { name: 'payroll_detail', type: 'route', icon: 'search', label: false, title: 'Detil Penggajian' }
                fields:
                    - { property: 'period.year', label: 'Tahun', type: 'text' }
                    - { property: 'period.month', label: 'Bulan', template: 'app/default/field_month.html.twig' }
                    - { property: 'employee', label: 'Karyawan' }
                    - { property: 'takeHomePay', label: 'Total Gaji', type: 'float', template: 'app/default/field_currency.html.twig' }

        PayrollDetail:
            role: '%env(string:SEMART_SECURITY_PAYROLL_MENU)%'
            class: 'KejawenLab\Application\SemartHris\Entity\PayrollDetail'
            controller: 'KejawenLab\Application\SemartHris\Controller\Admin\AdminController'
            disabled_actions: ['show', 'search', 'new', 'edit', 'delete']
            templates:
                list: 'app/payroll/detail.html.twig'
            list:
                role: '%env(string:SEMART_SECURITY_PAYROLL_MENU)%'
                title: 'Detil Penggajian'
                fields:
                    - { property: 'payroll.period.year', label: 'Tahun', type: 'text' }
                    - { property: 'payroll.period.month', label: 'Bulan', type: 'text', template: 'app/default/field_month.html.twig' }
                    - { property: 'payroll.employee', label: 'Karyawan', type: 'text' }
                    - { property: 'component.name', label: 'Komponen Gaji', type: 'text' }
                    - { property: 'component.state', label: 'Tipe', template: 'app/default/benefit_state.html.twig' }
                    - { property: 'benefitValue', label: 'Total', type: 'float', template: 'app/default/field_currency.html.twig' }

        CompanyCost:
            role: '%env(string:SEMART_SECURITY_PAYROLL_MENU)%'
            class: 'KejawenLab\Application\SemartHris\Entity\CompanyPayrollCost'
            controller: 'KejawenLab\Application\SemartHris\Controller\Admin\CompanyPayrollCostController'
            disabled_actions: ['show', 'search', 'new', 'edit', 'delete']
            templates:
                list: 'app/payroll/company_cost.html.twig'
            list:
                role: '%env(string:SEMART_SECURITY_PAYROLL_MENU)%'
                title: 'Beban Gaji Perusahaan'
                fields:
                    - { property: 'payroll.period.year', label: 'Tahun', type: 'text' }
                    - { property: 'payroll.period.month', label: 'Bulan', type: 'text', template: 'app/default/field_month.html.twig' }
                    - { property: 'payroll.employee', label: 'Karyawan', type: 'text' }
                    - { property: 'component.name', label: 'Komponen Gaji', type: 'text' }
                    - { property: 'component.state', label: 'Tipe', template: 'app/default/benefit_state.html.twig' }
                    - { property: 'benefitValue', label: 'Total', type: 'float', template: 'app/default/field_currency.html.twig' }
