easy_admin:
    entities:
        LeaveReason:
            role: '%env(string:SEMART_SECURITY_LEAVE_MENU)%'
            class: 'KejawenLab\Application\SemartHris\Entity\Reason'
            controller: 'KejawenLab\Application\SemartHris\Controller\Admin\ReasonController'
            templates:
                new: 'app/reason/new.html.twig'
                edit: 'app/reason/edit.html.twig'
            new:
                title: 'Tambah Alasan Cuti'
            edit:
                title: 'Edit Alasan Cuti'
            search:
                title: 'Alasan Cuti'
                dql_filter: "entity.type = 'l'"
                fields: ['code', 'name']
            form:
                fields:
                    - { type: 'group', css_class: 'col-sm-12' }
                    - { property: 'type', type: 'hidden', type_options: { data: 'l' } }
                    - { property: 'type_text', label: 'Jenis Alasan', type: 'choice', type_options: { disabled: true, mapped: false, attr: { class: 'static-select' }, data: 'l', choices: { CUTI: 'l' } } }
                    - { type: 'group', css_class: 'col-sm-6 new-row' }
                    - { property: 'code', label: 'Kode Alasan' }
                    - { type: 'group', css_class: 'col-sm-6' }
                    - { property: 'name', label: 'Alasan' }
            show:
                title: 'Detil Alasan Cuti'
                fields:
                    - { property: 'type', label: 'Jenis Alasan' }
                    - { property: 'code', label: 'Kode Alasan' }
                    - { property: 'name', label: 'Alasan' }
            list:
                role: '%env(string:SEMART_SECURITY_LEAVE_MENU)%'
                title: 'Alasan Cuti'
                dql_filter: "entity.type = 'l'"
                fields:
                    - { property: 'type_text', label: 'Jenis Alasan' }
                    - { property: 'code', label: 'Kode Alasan' }
                    - { property: 'name', label: 'Alasan' }

        AbsentReason:
            role: '%env(string:SEMART_SECURITY_ATTENDANCE_MENU)%'
            class: 'KejawenLab\Application\SemartHris\Entity\Reason'
            controller: 'KejawenLab\Application\SemartHris\Controller\Admin\ReasonController'
            templates:
                new: 'app/reason/new.html.twig'
                edit: 'app/reason/edit.html.twig'
            new:
                title: 'Tambah Alasan Ketidakhadiran'
            edit:
                title: 'Edit Alasan Ketidakhadiran'
            search:
                title: 'Alasan Ketidakhadiran'
                dql_filter: "entity.type = 'a'"
                fields: ['code', 'name']
            form:
                fields:
                    - { type: 'group', css_class: 'col-sm-12' }
                    - { property: 'type', type: 'hidden', type_options: { data: 'a' } }
                    - { property: 'type_text', label: 'Jenis Alasan', type: 'choice', type_options: { disabled: true, mapped: false, attr: { class: 'static-select' }, data: 'a', choices: { ABSENSI: 'a' } } }
                    - { type: 'group', css_class: 'col-sm-6' }
                    - { property: 'code', label: 'Kode Alasan' }
                    - { type: 'group', css_class: 'col-sm-6' }
                    - { property: 'name', label: 'Alasan' }
            show:
                title: 'Detil Alasan Ketidakhadiran'
                fields:
                    - { property: 'type', label: 'Jenis Alasan' }
                    - { property: 'code', label: 'Kode Alasan' }
                    - { property: 'name', label: 'Alasan' }
            list:
                role: '%env(string:SEMART_SECURITY_ATTENDANCE_MENU)%'
                title: 'Alasan Ketidakhadiran'
                dql_filter: "entity.type = 'a'"
                fields:
                    - { property: 'type_text', label: 'Jenis Alasan' }
                    - { property: 'code', label: 'Kode Alasan' }
                    - { property: 'name', label: 'Alasan' }
