easy_admin:
    entities:
        Skill:
            role: '%env(string:SEMART_SECURITY_MASTER_MENU)%'
            class: 'KejawenLab\Application\SemartHris\Entity\Skill'
            controller: 'KejawenLab\Application\SemartHris\Controller\Admin\SkillController'
            new:
                title: 'Tambah Keahlian'
            edit:
                title: 'Edit Keahlian'
            search:
                title: 'Keahlian'
                fields: ['name']
            form:
                fields:
                    - { type: 'group', label: 'Informasi Keahlian', icon: 'book', css_class: 'col-sm-12' }
                    - { property: 'skillGroup', label: 'Grup Keahlian', type: 'easyadmin_autocomplete' }
                    - { property: 'name', label: 'Keahlian' }
            show:
                title: 'Detil Keahlian'
                fields:
                    - { type: 'group', css_class: 'col-sm-6' }
                    - { property: 'skillGroup', label: 'Grup Keahlian' }
                    - { type: 'group', css_class: 'col-sm-6' }
                    - { property: 'name', label: 'Keahlian' }
            list:
                role: '%env(string:SEMART_SECURITY_MASTER_MENU)%'
                title: 'Keahlian'
                fields:
                    - { property: 'skillGroup', label: 'Grup Keahlian' }
                    - { property: 'name', label: 'Keahlian' }

        SkillGroup:
            role: '%env(string:SEMART_SECURITY_MASTER_MENU)%'
            class: 'KejawenLab\Application\SemartHris\Entity\SkillGroup'
            controller: 'KejawenLab\Application\SemartHris\Controller\Admin\AdminController'
            new:
                title: 'Tambah Grup Keahlian'
            edit:
                title: 'Edit Grup Keahlian'
            search:
                title: 'Grup Keahlian'
                fields: ['name']
            form:
                fields:
                    - { type: 'group', css_class: 'col-sm-6' }
                    - { property: 'parent', label: 'Grup Induk', type: 'easyadmin_autocomplete' }
                    - { type: 'group', css_class: 'col-sm-6' }
                    - { property: 'name', label: 'Grup Keahlian' }
            show:
                title: 'Detil Grup Keahlian'
                fields:
                    - { property: 'parent', label: 'GrupInduk' }
                    - { property: 'name', label: 'Grup Keahlian' }
            list:
                role: '%env(string:SEMART_SECURITY_MASTER_MENU)%'
                title: 'Grup Keahlian'
                fields:
                    - { property: 'parent', label: 'Grup Induk' }
                    - { property: 'name', label: 'Grup Keahlian' }
