api_platform:
    title: '%env(string:SEMART_NAME)%'
    description: '%env(string:SEMART_API_DESCRIPTION)%'
    version: !php/const KejawenLab\Application\SemartHris\Kernel::SEMART_VERSION
    collection:
        order: 'DESC'
        order_parameter_name: 'o'
        pagination:
            enabled: true
            client_enabled: true
            client_items_per_page: true
            items_per_page: 17
            maximum_items_per_page: 99
            page_parameter_name: 'p'
            enabled_parameter_name: 'ep'
            items_per_page_parameter_name: 'i'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']

services:
    api_platform.filters.code_search:
        parent:    'api_platform.doctrine.orm.search_filter'
        arguments: [ { code: 'partial' } ]
        tags:      [ { name: 'api_platform.filter', id: 'code.search' } ]

    api_platform.filters.short_name_search:
        parent:    'api_platform.doctrine.orm.search_filter'
        arguments: [ { shortName: 'partial' } ]
        tags:      [ { name: 'api_platform.filter', id: 'short_name.search' } ]

    api_platform.filters.name_search:
        parent:    'api_platform.doctrine.orm.search_filter'
        arguments: [ { name: 'partial' } ]
        tags:      [ { name: 'api_platform.filter', id: 'name.search' } ]

    api_platform.filters.full_name_search:
        parent:    'api_platform.doctrine.orm.search_filter'
        arguments: [ { fullName: 'partial' } ]
        tags:      [ { name: 'api_platform.filter', id: 'full_name.search' } ]
