security:
    encoders:
        KejawenLab\Application\SemartHris\Component\User\Model\UserInterface: bcrypt
#            algorithm: 'argon2i' #change to argon2i encoder after stable release

    access_decision_manager:
        strategy: affirmative

    role_hierarchy:
        ROLE_EMPLOYEE: ROLE_EMPLOYEE
        ROLE_HRSTAFF: [ROLE_HRSTAFF, ROLE_EMPLOYEE]
        ROLE_HRSUPERVISOR: [ROLE_HRSUPERVISOR, ROLE_HRSTAFF]
        ROLE_HRMANAGER: [ROLE_HRMANAGER, ROLE_HRSUPERVISOR]
        ROLE_HRGENERAL_MANAGER: [ROLE_HRGENERAL_MANAGER, ROLE_HRMANAGER]
        ROLE_HRDIRECTOR: [ROLE_HRDIRECTOR, ROLE_HRGENERAL_MANAGER]
        ROLE_TOP_LEVEL_MANAGEMENT: [ROLE_TOP_LEVEL_MANAGEMENT, ROLE_EMPLOYEE]
        ROLE_SUPER_ADMIN: [ROLE_TOP_LEVEL_MANAGEMENT, ROLE_HRDIRECTOR]

    providers:
        semarthris:
            id: KejawenLab\Application\SemartHris\Security\Provider\UserProvider

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: semarthris
                check_path: login_check
                csrf_token_generator: security.csrf.token_manager
            logout:
                path: logout
                target: easyadmin
            anonymous:    true

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_EMPLOYEE }
