twig:
    paths: ['%kernel.project_dir%/templates/']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        semarthris_name: !php/const KejawenLab\Application\SemartHris\Kernel::SEMART_CANONICAL
        semarthris_version: !php/const KejawenLab\Application\SemartHris\Kernel::SEMART_VERSION
        default_role: 'ROLE_EMPLOYEE'
        date_format_long: '%env(string:SEMART_DATE_FORMAT_LONG)%'
        date_format: '%env(string:SEMART_DATE_FORMAT)%'
        datetime_format: '%env(string:SEMART_DATE_TIME_FORMAT)%'
        time_format: '%env(string:SEMART_TIME_FORMAT)%'
        hour_format: '%env(string:SEMART_HOUR_FORMAT)%'
        currency_prefix: '%env(string:SEMART_CURRENCY_PREFIX)%'
        currency_surfix: '%env(string:SEMART_CURRENCY_SURFIX)%'
        decimal_precision: '%env(int:SEMART_DECIMAL_PRECISION)%'
        decimal_point: '%env(string:SEMART_DECIMAL_POINT)%'
        thousand_separator: '%env(string:SEMART_THOUSAND_SEPARATOR)%'
