###
# This setting is used only in development environment
# The infrastructure is already in production but the application need to be make sure
###
version: '3'
services:
    app:
        build: .
        environment:
            SYMFONY_ENV: dev
            SEMART_DB_DRIVER: pgsql
            SEMART_DB_USER: semarthris
            SEMART_DB_PASSWORD: semarthris
            SEMART_DB_HOST: db
            SEMART_DB_PORT: 5432
            SEMART_DB_NAME: semarthris
        volumes:
            - ./uploads:/semarthris/uploads:rw
        links:
            - db
            - session
        depends_on:
            - db
            - session

    db:
        image: postgres:alpine
        restart: always
        environment:
            POSTGRES_USER: semarthris
            POSTGRES_PASSWORD: semarthris
            POSTGRES_DB: semarthris
        volumes:
            - ./database:/var/lib/postgresql/data:rw

    session:
        image: redis:alpine

    adminer:
        image: adminer
        ports:
            - 8080:8080

    balancer:
        image: dockercloud/haproxy:latest
        ports:
            - 8000:80
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        links:
            - app
        depends_on:
            - app
