services:
    _defaults:
        public: true
    KejawenLab\Application\SemartHris\Form\Manipulator\CompanyAddressManipulator:
        lazy: true
        arguments:
            - '@KejawenLab\Application\SemartHris\Form\DataTransformer\CompanyTransformer'
            - { city: '@KejawenLab\Application\SemartHris\Form\DataTransformer\CityTransformer' }
            - [ '@KejawenLab\Application\SemartHris\Form\EventListener\RemoveCityTextFieldSubscriber', '@KejawenLab\Application\SemartHris\Form\EventListener\DefaultAddressCheckerSubscriber' ]

    KejawenLab\Application\SemartHris\Form\Manipulator\CompanyDepartmentManipulator:
        lazy: true
        arguments:
            - { company: '@KejawenLab\Application\SemartHris\Form\DataTransformer\CompanyTransformer' }

    KejawenLab\Application\SemartHris\Form\Manipulator\EmployeeManipulator:
        lazy: true
        arguments:
            - '@KejawenLab\Application\SemartHris\Form\DataTransformer\CompanyTransformer'
            - '@KejawenLab\Application\SemartHris\Form\DataTransformer\JobLevelTransformer'
            - { cityOfBirth: '@KejawenLab\Application\SemartHris\Form\DataTransformer\CityTransformer', department: '@KejawenLab\Application\SemartHris\Form\DataTransformer\DepartmentTransformer', jobTitle: '@KejawenLab\Application\SemartHris\Form\DataTransformer\JobTitleTransformer', supervisor: '@KejawenLab\Application\SemartHris\Form\DataTransformer\EmployeeTransformer', contract: '@KejawenLab\Application\SemartHris\Form\DataTransformer\ContractTransformer' }
            - [ '@KejawenLab\Application\SemartHris\Form\EventListener\RemoveCityTextFieldSubscriber', '@KejawenLab\Application\SemartHris\Form\EventListener\RemoveDepartmentTextFieldSubscriber', '@KejawenLab\Application\SemartHris\Form\EventListener\RemoveJobTitleTextFieldSubscriber', '@KejawenLab\Application\SemartHris\Form\EventListener\RemoveSupervisorTextFieldSubscriber', '@KejawenLab\Application\SemartHris\Form\EventListener\RemoveContractTextFieldSubscriber' ]

    KejawenLab\Application\SemartHris\Form\Manipulator\PlacementManipulator:
        lazy: true
        arguments:
            - { department: '@KejawenLab\Application\SemartHris\Form\DataTransformer\DepartmentTransformer', jobTitle: '@KejawenLab\Application\SemartHris\Form\DataTransformer\JobTitleTransformer', supervisor: '@KejawenLab\Application\SemartHris\Form\DataTransformer\EmployeeTransformer', contract: '@KejawenLab\Application\SemartHris\Form\DataTransformer\ContractTransformer' }
            - [ '@KejawenLab\Application\SemartHris\Form\EventListener\RemoveDepartmentTextFieldSubscriber', '@KejawenLab\Application\SemartHris\Form\EventListener\RemoveJobTitleTextFieldSubscriber', '@KejawenLab\Application\SemartHris\Form\EventListener\RemoveSupervisorTextFieldSubscriber', '@KejawenLab\Application\SemartHris\Form\EventListener\RemoveContractTextFieldSubscriber' ]

    KejawenLab\Application\SemartHris\Form\Manipulator\MutationManipulator:
        lazy: true
        arguments:
            - { newDepartment: '@KejawenLab\Application\SemartHris\Form\DataTransformer\DepartmentTransformer', newJobTitle: '@KejawenLab\Application\SemartHris\Form\DataTransformer\JobTitleTransformer', newSupervisor: '@KejawenLab\Application\SemartHris\Form\DataTransformer\EmployeeTransformer', contract: '@KejawenLab\Application\SemartHris\Form\DataTransformer\ContractTransformer' }
            - [ '@KejawenLab\Application\SemartHris\Form\EventListener\RemoveDepartmentTextFieldSubscriber', '@KejawenLab\Application\SemartHris\Form\EventListener\RemoveJobTitleTextFieldSubscriber', '@KejawenLab\Application\SemartHris\Form\EventListener\RemoveSupervisorTextFieldSubscriber', '@KejawenLab\Application\SemartHris\Form\EventListener\RemoveContractTextFieldSubscriber' ]

    KejawenLab\Application\SemartHris\Form\Manipulator\TaxHistoryManipulator:
        lazy: true
        arguments:
            - {}
            - [ '@KejawenLab\Application\SemartHris\Form\EventListener\RemoveEmptyTaxHistorySubscriber' ]

    KejawenLab\Application\SemartHris\Form\Manipulator\EmployeeAddressManipulator:
        lazy: true
        arguments:
            - '@KejawenLab\Application\SemartHris\Form\DataTransformer\EmployeeTransformer'
            - { city: '@KejawenLab\Application\SemartHris\Form\DataTransformer\CityTransformer' }
            - [ '@KejawenLab\Application\SemartHris\Form\EventListener\RemoveCityTextFieldSubscriber', '@KejawenLab\Application\SemartHris\Form\EventListener\DefaultAddressCheckerSubscriber' ]

    KejawenLab\Application\SemartHris\Form\Manipulator\ContractManipulator:
        lazy: true
        arguments:
            - { tags: '@KejawenLab\Application\SemartHris\Form\DataTransformer\TagTransformer' }
            - [ '@KejawenLab\Application\SemartHris\Form\EventListener\RemoveTagsTextFieldSubscriber' ]

    KejawenLab\Application\SemartHris\Form\Manipulator\ReasonManipulator:
        lazy: true
        arguments:
            - {}
            - [ '@KejawenLab\Application\SemartHris\Form\EventListener\RemoveTypeTextFieldSubscriber' ]

    KejawenLab\Application\SemartHris\Form\Manipulator\BenefitHistoryManipulator:
        lazy: true
        arguments:
            - { contract: '@KejawenLab\Application\SemartHris\Form\DataTransformer\ContractTransformer', component: '@KejawenLab\Application\SemartHris\Form\DataTransformer\SalaryComponentTransformer' }
            - [ '@KejawenLab\Application\SemartHris\Form\EventListener\RemoveContractTextFieldSubscriber', '@KejawenLab\Application\SemartHris\Form\EventListener\RemoveComponentTextFieldSubscriber' ]

    KejawenLab\Application\SemartHris\Form\Manipulator\UserManipulator:
        lazy: true
        arguments:
            - { roles: '@KejawenLab\Application\SemartHris\Form\DataTransformer\RoleTransformer' }
            - [ '@KejawenLab\Application\SemartHris\Form\EventListener\EncodePasswordSubscriber' ]

    KejawenLab\Application\SemartHris\Form\Manipulator\AttendanceManipulator:
        lazy: true
        arguments:
            - { reason: '@KejawenLab\Application\SemartHris\Form\DataTransformer\ReasonTransformer' }
            - [ '@KejawenLab\Application\SemartHris\Form\EventListener\RemoveReasonTextFieldSubscriber' ]

    KejawenLab\Application\SemartHris\Form\Manipulator\LeaveManipulator:
        lazy: true
        arguments:
            - { reason: '@KejawenLab\Application\SemartHris\Form\DataTransformer\ReasonTransformer' }
            - [ '@KejawenLab\Application\SemartHris\Form\EventListener\RemoveReasonTextFieldSubscriber' ]

    KejawenLab\Application\SemartHris\Form\Manipulator\SalaryAllowanceManipulator:
        lazy: true
        arguments:
            - { component: '@KejawenLab\Application\SemartHris\Form\DataTransformer\SalaryComponentTransformer' }
            - [ '@KejawenLab\Application\SemartHris\Form\EventListener\RemoveComponentTextFieldSubscriber' ]

    KejawenLab\Application\SemartHris\Form\Manipulator\SalaryBenefitManipulator:
        lazy: true
        arguments:
            - { component: '@KejawenLab\Application\SemartHris\Form\DataTransformer\SalaryComponentTransformer' }
            - [ '@KejawenLab\Application\SemartHris\Form\EventListener\RemoveBenefitValueFieldSubscriber', '@KejawenLab\Application\SemartHris\Form\EventListener\RemoveComponentTextFieldSubscriber' ]
